name: Docker build and publish

on: 
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_CONTAINERD: 1

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:master,network=host

      # Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ github.sha }}  # Cache key based on OS and commit SHA.
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build dockerpi:vm
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dockerpi-vm
          load: true
          tags: brrock/dockerpi:vm
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build dockerpi
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dockerpi
          load: true
          tags: brrock/dockerpi:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Log image data
        run: docker images brrock/dockerpi

      # Publish steps (only run on main branch)
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: brrock
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push --all-tags brrock/dockerpi