name: Raspberry Pi Kernel Build

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Specific kernel version (optional)'
        required: false
        default: ''
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly build to check for updates

jobs:
  build-rpi-kernel:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          wget \
          bc \
          libncurses5-dev \
          gcc-aarch64-linux-gnu \
          flex \
          bison \
          make \
          gcc \
          device-tree-compiler \
          jq \
          curl \
          ccache \
          tree

    # Cache GitHub Actions
    - name: Prepare ccache
      uses: actions/cache@v4
      with:
        path: |
          ~/.ccache
          /tmp/ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    # Cache kernel source
    - name: Check for Cached Kernel Source
      id: kernel-cache
      uses: actions/cache@v4
      with:
        path: /tmp/rpi-linux/kernel
        key: rpi-linux-kernel-${{ hashFiles('**/latest-kernel-version.txt') }}
        restore-keys: |
          rpi-linux-kernel-

    - name: Clone Raspberry Pi Linux Kernel
      if: steps.kernel-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /tmp/rpi-linux/kernel
        cd /tmp/rpi-linux/kernel
        git clone --depth 1 https://github.com/raspberrypi/linux.git .
        git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) # Checkout the latest tag
    # Cached build artifacts
    - name: Check for Cached Kernel Build
      id: kernel-build-cache
      uses: actions/cache@v4
      with:
        path: |
          /tmp/rpi-linux/kernel/arch/arm64/boot/Image
          /tmp/rpi-linux/kernel/arch/arm64/boot/dts
        key: rpi-linux-kernel-build-${{ steps.kernel_version.outputs.version }}-${{ hashFiles('/tmp/rpi-linux/kernel/.config') }}

    - name: Configure Kernel
      if: steps.kernel-build-cache.outputs.cache-hit != 'true'
      run: |
        cd /tmp/rpi-linux/kernel
        
        # Enable ccache
        export PATH="/usr/lib/ccache:$PATH"
        export CCACHE_DIR=~/.ccache
        ccache -z
        
        # Kernel configuration
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig

        # Add custom configuration
        cat >> .config << EOF
        # ARM64 QEMU and Raspberry Pi specific configurations
        CONFIG_ARCH_BCM2835=y
        CONFIG_ARCH_BCM2710=y
        CONFIG_ARCH_BCM2711=y
        CONFIG_ARCH_BCM2712=y
        CONFIG_ARM64=y
        CONFIG_RANDOMIZE_BASE=y
        CONFIG_CMDLINE="console=ttyAMA0"

        # QEMU Virtualization support
        CONFIG_VIRTUALIZATION=y
        CONFIG_KVM=y
        CONFIG_KVM_ARM_HOST=y

        # File systems
        CONFIG_OVERLAY_FS=y
        CONFIG_SQUASHFS=y
        CONFIG_NFS_FS=y
        CONFIG_ROOT_NFS=y

        # Network
        CONFIG_NETDEVICES=y
        CONFIG_NET_9P=y
        CONFIG_NET_9P_VIRTIO=y
        CONFIG_VIRTIO_NET=y

        # Block devices
        CONFIG_VIRTIO_BLK=y
        CONFIG_BLK_DEV_SD=y

        # Other useful configs
        CONFIG_MODULES=y
        CONFIG_MODULE_UNLOAD=y
        CONFIG_MODVERSIONS=y
        EOF

    - name: Build Kernel
      if: steps.kernel-build-cache.outputs.cache-hit != 'true'
      run: |
        cd /tmp/rpi-linux/kernel
        
        # Enable ccache
        export PATH="/usr/lib/ccache:$PATH"
        export CCACHE_DIR=~/.ccache
        
        # Build kernel
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) Image dtbs modules
        
        # Show ccache statistics
        ccache -s

    - name: Prepare Output Directory
      run: |
        mkdir -p ${{ github.workspace }}/rpi-kernel-output
        sudo chown $USER /tmp/rpi-linux/kernel/arch/arm64 -R -v
        tree /tmp/rpi-linux/kernel/arch/arm64  
        # Copy kernel
        cp /tmp/rpi-linux/kernel/arch/arm64/boot/Image ${{ github.workspace }}/rpi-kernel-output/kernel -v
        
        # Find and copy device trees
        echo "Finding DTB files..."
        dtb_files=$(find /tmp/rpi-linux/kernel -name "*.dtb")
        
        # Counter for DTB files
        dtb_count=0
        
        for dtb in $dtb_files; do
          # Extract filename
          filename=$(basename "$dtb")
          
          # Check for specific Pi models or interesting DTBs
          if [[ "$filename" == *"rpi-4-b"* || "$filename" == *"rpi-5-b"* || "$filename" == *"versatile"* ]]; then
            echo "Copying DTB: $dtb"
            cp "$dtb" "${{ github.workspace }}/rpi-kernel-output/dtb_${dtb_count}.dtb"
            ((dtb_count++))
          fi
        done
        
        echo "Found and copied $dtb_count DTB files"

    - name: Create Kernel Modules Archive
      run: |
        cd /tmp/rpi-linux/kernel
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=${{ github.workspace }}/rpi-kernel-output/modules modules_install
        cd ${{ github.workspace }}/rpi-kernel-output/modules
        tar -czvf ../kernel-modules.tar.gz .

    - name: Generate Build Info
      run: |
        cd /tmp/rpi-linux/kernel
        echo "Kernel Version: ${{ steps.kernel_version.outputs.version }}" > ${{ github.workspace }}/rpi-kernel-output/build-info.txt
        echo "Build Date: $(date)" >> ${{ github.workspace }}/rpi-kernel-output/build-info.txt
        make kernelrelease >> ${{ github.workspace }}/rpi-kernel-output/build-info.txt
        
        # List all copied DTB files
        echo -e "\nCopied DTB Files:" >> ${{ github.workspace }}/rpi-kernel-output/build-info.txt
        ls ${{ github.workspace }}/rpi-kernel-output/*.dtb >> ${{ github.workspace }}/rpi-kernel-output/build-info.txt

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rpi-arm64-kernel
        path: ${{ github.workspace }}/rpi-kernel-output
        retention-days: 30

    - name: List Output Contents
      run: |
        echo "Output directory contents:"
        ls -la ${{ github.workspace }}/rpi-kernel-output

    # Optional: Commit and push kernel artifacts back to repo
    - name: Commit Kernel Artifacts
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Stage kernel output
        git add rpi-kernel-output
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Raspberry Pi ARM64 Kernel Artifacts (${GITHUB_SHA})"
          git push
        fi
      # Only commit if on main branch
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

